package com.square.getmedoc.db.model;

// Generated Sep 2, 2013 7:42:39 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", catalog = "getmedoc")
public class Address implements java.io.Serializable {

	private Long addressid;
	private Appuser appuser;
	private String line1;
	private String line2;
	private String line3;
	private String city;
	private String state;
	private String country;
	private String zip;
	private int type;
	private Integer preferred;

	public Address() {
	}

	public Address(Appuser appuser, String line1, String city, int type) {
		this.appuser = appuser;
		this.line1 = line1;
		this.city = city;
		this.type = type;
	}

	public Address(Appuser appuser, String line1, String line2, String line3,
			String city, String state, String country, String zip, int type,
			Integer preferred) {
		this.appuser = appuser;
		this.line1 = line1;
		this.line2 = line2;
		this.line3 = line3;
		this.city = city;
		this.state = state;
		this.country = country;
		this.zip = zip;
		this.type = type;
		this.preferred = preferred;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "addressid", unique = true, nullable = false)
	public Long getAddressid() {
		return this.addressid;
	}

	public void setAddressid(Long addressid) {
		this.addressid = addressid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "appuserid", nullable = false)
	public Appuser getAppuser() {
		return this.appuser;
	}

	public void setAppuser(Appuser appuser) {
		this.appuser = appuser;
	}

	@Column(name = "line1", nullable = false, length = 256)
	public String getLine1() {
		return this.line1;
	}

	public void setLine1(String line1) {
		this.line1 = line1;
	}

	@Column(name = "line2", length = 256)
	public String getLine2() {
		return this.line2;
	}

	public void setLine2(String line2) {
		this.line2 = line2;
	}

	@Column(name = "line3", length = 256)
	public String getLine3() {
		return this.line3;
	}

	public void setLine3(String line3) {
		this.line3 = line3;
	}

	@Column(name = "city", nullable = false, length = 256)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", length = 256)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "country", length = 256)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "zip", length = 45)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "preferred")
	public Integer getPreferred() {
		return this.preferred;
	}

	public void setPreferred(Integer preferred) {
		this.preferred = preferred;
	}

}
