package com.square.getmedoc.db.model;

// Generated Oct 22, 2013 11:20:48 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Choice generated by hbm2java
 */
@Entity
@Table(name = "choice", catalog = "getmedoc")
public class Choice implements java.io.Serializable {

	private Long id;
	private int choiceid;
	private int choiceindex;
	private String description;
	private String locale;
	private Set<Specializations> specializationses = new HashSet<Specializations>(
			0);
	private Set<Degree> degrees = new HashSet<Degree>(0);

	public Choice() {
	}

	public Choice(int choiceid, int choiceindex, String locale) {
		this.choiceid = choiceid;
		this.choiceindex = choiceindex;
		this.locale = locale;
	}

	public Choice(int choiceid, int choiceindex, String description,
			String locale, Set<Specializations> specializationses,
			Set<Degree> degrees) {
		this.choiceid = choiceid;
		this.choiceindex = choiceindex;
		this.description = description;
		this.locale = locale;
		this.specializationses = specializationses;
		this.degrees = degrees;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "choiceid", nullable = false)
	public int getChoiceid() {
		return this.choiceid;
	}

	public void setChoiceid(int choiceid) {
		this.choiceid = choiceid;
	}

	@Column(name = "choiceindex", nullable = false)
	public int getChoiceindex() {
		return this.choiceindex;
	}

	public void setChoiceindex(int choiceindex) {
		this.choiceindex = choiceindex;
	}

	@Column(name = "description", length = 1024)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "locale", nullable = false, length = 45)
	public String getLocale() {
		return this.locale;
	}

	public void setLocale(String locale) {
		this.locale = locale;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "choice")
	public Set<Specializations> getSpecializationses() {
		return this.specializationses;
	}

	public void setSpecializationses(Set<Specializations> specializationses) {
		this.specializationses = specializationses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "choice")
	public Set<Degree> getDegrees() {
		return this.degrees;
	}

	public void setDegrees(Set<Degree> degrees) {
		this.degrees = degrees;
	}

}
