package com.square.getmedoc.db.model;

// Generated Oct 22, 2013 11:20:48 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Doctor generated by hbm2java
 */
@Entity
@Table(name = "doctor", catalog = "getmedoc")
public class Doctor implements java.io.Serializable {

	private Long id;
	private Appuser appuser;
	private Integer specilization;
	private Integer degree;
	private String expertise;

	public Doctor() {
	}

	public Doctor(Appuser appuser) {
		this.appuser = appuser;
	}

	public Doctor(Appuser appuser, Integer specilization, Integer degree,
			String expertise) {
		this.appuser = appuser;
		this.specilization = specilization;
		this.degree = degree;
		this.expertise = expertise;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "doctorid", nullable = false)
	public Appuser getAppuser() {
		return this.appuser;
	}

	public void setAppuser(Appuser appuser) {
		this.appuser = appuser;
	}

	@Column(name = "specilization")
	public Integer getSpecilization() {
		return this.specilization;
	}

	public void setSpecilization(Integer specilization) {
		this.specilization = specilization;
	}

	@Column(name = "degree")
	public Integer getDegree() {
		return this.degree;
	}

	public void setDegree(Integer degree) {
		this.degree = degree;
	}

	@Column(name = "expertise", length = 1024)
	public String getExpertise() {
		return this.expertise;
	}

	public void setExpertise(String expertise) {
		this.expertise = expertise;
	}

}
