package com.square.getmedoc.db.model;

// Generated Sep 3, 2013 12:19:59 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Webaddress generated by hbm2java
 */
@Entity
@Table(name = "webaddress", catalog = "getmedoc")
public class Webaddress implements java.io.Serializable {

	private Long webaddressid;
	private Appuser appuser;
	private int type;
	private String email;
	private Integer preferred;

	public Webaddress() {
	}

	public Webaddress(Appuser appuser, int type, String email) {
		this.appuser = appuser;
		this.type = type;
		this.email = email;
	}

	public Webaddress(Appuser appuser, int type, String email, Integer preferred) {
		this.appuser = appuser;
		this.type = type;
		this.email = email;
		this.preferred = preferred;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "webaddressid", unique = true, nullable = false)
	public Long getWebaddressid() {
		return this.webaddressid;
	}

	public void setWebaddressid(Long webaddressid) {
		this.webaddressid = webaddressid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "appuserid", nullable = false)
	public Appuser getAppuser() {
		return this.appuser;
	}

	public void setAppuser(Appuser appuser) {
		this.appuser = appuser;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "email", nullable = false, length = 256)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "preferred")
	public Integer getPreferred() {
		return this.preferred;
	}

	public void setPreferred(Integer preferred) {
		this.preferred = preferred;
	}

}
